version: '3.8'

services:
  app:
    build:
      context: ./backend
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    #  - rabbitmq
    environment:
      MONGO_URI: mongodb://mongo:27017/mydb
      #RABBITMQ_URI: amqp://rabbitmq:5672
    networks:
      - my-network

  mongo:
    image: mongo:latest
    container_name: mongo-db
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

  #rabbitmq:
  #  image: rabbitmq:management
  #  container_name: rabbitmq
  #  ports:
  #    - "15672:15672"  # RabbitMQ management UI
  #    - "5672:5672"    # RabbitMQ main port
  #  networks:
  #    - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:
